version: '3.8'

services:
  api:
    build: .
    container_name: hms_api_server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - GCP_PROJECT_ID=empyrean-yeti-466217-c4
      - GCS_BUCKET_NAME=vanshika-hms-orders-bucket
      - DB_USER=postgres
      - DB_PASSWORD=password123
      - DB_HOST=host.docker.internal
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud:ro  # Mounts host machine local ADC context safely into Docker
    depends_on:
      - hms_shard_0
      - hms_shard_1
      - hms_shard_2

  hms_shard_0:
    image: postgres:15
    container_name: hms_shard_0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: orders_shard_0
    ports:
      - "5431:5432"
    volumes:
      - shard_0_data:/var/lib/postgresql/data

  hms_shard_1:
    image: postgres:15
    container_name: hms_shard_1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: orders_shard_1
    ports:
      - "5432:5432"
    volumes:
      - shard_1_data:/var/lib/postgresql/data

  hms_shard_2:
    image: postgres:15
    container_name: hms_shard_2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: orders_shard_2
    ports:
      - "5433:5432"
    volumes:
      - shard_2_data:/var/lib/postgresql/data

volumes:
  shard_0_data:
  shard_1_data:
  shard_2_data: